FROM python:3 as builder

ENV PYTHONUNBUFFERED 1 

WORKDIR /app 

ADD .  /app
 
FROM python:3.9.0rc1-alpine3.12

ENV PYTHONUNBUFFERED 1 

WORKDIR /app

COPY --from=builder .   /app

RUN pip install -r requirements.txt

