FROM python:3 as builder

ENV PYTHONUNBUFFERED 1 

WORKDIR /app 

COPY . /app 

RUN pip install -r requirements.txt

COPY . /app

FROM python:3.8.5-alpine3.12

WORKDIR /app/python/ 

COPY --from=builder  .   /app/python/ 

