FROM node:9-slim as builder 

WORKDIR /app 

COPY package.json ./app 

RUN npm install 

COPY . /app

FROM node:10.22.0-alpine3.10

WORKDIR /app 

COPY --from=builder /app   /app 

CMD ["npm","start"]
